### ISSUE TITLE
jsk_smart_apps is super heavy

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_smart_apps#42]
@furushchev Please make it light.

```
$ time git clone https://github.com/jsk-ros-pkg/jsk_smart_apps.git
Cloning into 'jsk_smart_apps'...
remote: Counting objects: 13962, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 13962 (delta 21), reused 31 (delta 16)
Receiving objects: 100% (13962/13962), 384.98 MiB | 258 KiB/s, done.
Resolving deltas: 100% (4707/4707), done.
git clone https://github.com/jsk-ros-pkg/jsk_smart_apps.git  30.90s user 13.73s system 2% cpu 34:44.58 total
lueda has logged on pts/14 from :0.                                             
```

**Comment by garaemon** [comment]
boost and tf are heavy
```
$ ls -lh
合計 180M
-rw-r--r-- 1 lueda lueda 100M Jan 11 20:14 boost.framework.zip
-rw-r--r-- 1 lueda lueda 195K Jan 11 20:14 geometry_msgs.framework.zip
-rw-r--r-- 1 lueda lueda  27M Jan 11 20:14 log4cxx.framework.zip
-rw-r--r-- 1 lueda lueda  97K Jan 11 20:14 nav_msgs.framework.zip
-rw-r--r-- 1 lueda lueda  42M Jan 11 20:14 ros.framework.zip
-rw-r--r-- 1 lueda lueda  25K Jan 11 20:14 rosgraph_msgs.framework.zip
-rw-r--r-- 1 lueda lueda 303K Jan 11 20:14 sensor_msgs.framework.zip
-rw-r--r-- 1 lueda lueda 306K Jan 11 20:14 std_msgs.framework.zip
-rw-r--r-- 1 lueda lueda  12M Jan 11 20:14 tf.framework.zip
```

**Comment by k-okada** [comment]
please consider using jsk-ros-pkg/archives as
https://github.com/jsk-ros-pkg/jsk_common/pull/690

--
◉ Kei Okada

**Comment by furushchev** [comment]
I intend to move frameworks zip to jsk-ros-pkg/archives repo.

as reported [many blogs](http://www.d-wood.com/blog/2014/10/03_6965.html), it seems to be tough work to remove large files from git.
According to the blog site above,

1. `git rm` zip files
2. `git filter-branch -f --index-filter 'git rm --cached --ignore-unmatch <zip files>' HEAD` each zip files
3. `git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d`
4. `git reflog expire --expire=now --all`
5. `git gc --prune=now`

but still .git has large cache files

```bash
$ cd /path/to/reposirory
$ du -hs .git/objects
296M	.git/objects
```

Is there any idea to shrink repository size?

**Comment by furushchev** [comment]
[github suggests](https://help.github.com/articles/working-with-large-files/) to use [`bfg` app](https://rtyley.github.io/bfg-repo-cleaner/) to remove big file from git repo.
So I will try this.

**Comment by furushchev** [comment]
This tool changes all branches and tags, so I think those who is committable to this repo is good to use.

**Comment by garaemon** [comment]
done

```
java -jar ~/Downloads/bfg-1.12.0.jar --strip-blobs-bigger-than 10M  jsk_smart_apps.git
java -jar ~/Downloads/bfg-1.12.0.jar --delete-files '*.zip' jsk_smart_apps.git
```

**Comment by garaemon** [comment]
not yet
bfg rewrites read-only branch and it is rejected by github.

**Comment by garaemon** [comment]
Done

1. Do not clone repository with `--mirror` option not to write refs branches 
2. removed *.zip and files over 10M

```
$ time git clone git@github.com:jsk-ros-pkg/jsk_smart_apps.git
Cloning into 'jsk_smart_apps'...
remote: Counting objects: 13942, done.
remote: Compressing objects: 100% (8817/8817), done.
remote: Total 13942 (delta 4710), reused 13863 (delta 4675)
Receiving objects: 100% (13942/13942), 17.41 MiB | 2.04 MiB/s, done.
Resolving deltas: 100% (4710/4710), done.
hub clone git@github.com:jsk-ros-pkg/jsk_smart_apps.git  2.56s user 0.62s system 17% cpu 18.247 total

```
