### ISSUE TITLE
cannot compile jsk_smart_gui

### ISSUE THREAD

**Issue by h-kamada** [jsk-ros-pkg/jsk_smart_apps#44]
```
CMake Error: Attempt to add a custom rule to output "/home/h-kamada/ros/hydro/devel/share/roseus/ros/jsk_smart_gui/manifest.l.rule" which already has a custom rule.
CMake Error at /home/h-kamada/ros/hydro/build/jsk_smart_gui/cmake/jsk_smart_gui-genmsg.cmake:65 (add_custom_target):
  add_custom_target cannot create target
  "jsk_smart_gui_generate_messages_eus" because another target with the same
  name already exists.  The existing target is a custom target created in
  source directory
  "/home/h-kamada/ros/hydro/src/jsk-ros-pkg/jsk_smart_apps/jsk_smart_gui".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /opt/ros/hydro/share/genmsg/cmake/genmsg-extras.cmake:299 (include)
  catkin.cmake:11 (generate_messages)
  CMakeLists.txt:2 (include)


-- set EUSDIR to /home/h-kamada/ros/hydro_parent/devel/share/euslisp/jskeus/eus/
-- set ARCHDIR to Linux64
-- Set euslisp_INCLUDE_DIRS to /home/h-kamada/ros/hydro_parent/devel/share/euslisp/jskeus/eus//include
-- Configuring incomplete, errors occurred!
[jsk_smart_gui] <== '/home/h-kamada/ros/hydro/build/jsk_smart_gui/build_env.sh /usr/bin/cmake /home/h-kamada/ros/hydro/src/jsk-ros-pkg/jsk_smart_apps/jsk_smart_gui -DCATKIN_DEVEL_PREFIX=/home/h-kamada/ros/hydro/devel -DCMAKE_INSTALL_PREFIX=/home/h-kamada/ros/hydro/install' failed with return code '1'

```

**Comment by h-kamada** [comment]
we can compile it with `catkin build jsk_smart_gui`

**Comment by h-kamada** [comment]
strange behavior

**Comment by h-kamada** [comment]
I have same error message in jsk_rviz_plugins...

**Comment by h-kamada** [comment]
I have apt packages and I try to overwrite them in my catkin workspace.

**Comment by k-okada** [comment]
please update to latest roseus that includes
https://github.com/jsk-ros-pkg/jsk_roseus/pull/223, and send me all
messages, gist (https://gist.github.com/) may useful in this case

--
◉ Kei Okada

**Comment by k-okada** [comment]
sorry I can not reproduce this
```
k-okada@ubuntu:~/catkin_ws/ws_msg$ catkin build jsk_rviz_plugins --force-cmake
------------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/k-okada/catkin_ws/ws_euslisp/devel:/opt/ros/hydro
Workspace:                   /home/k-okada/catkin_ws/ws_msg
Source Space:       [exists] /home/k-okada/catkin_ws/ws_msg/src
Build Space:        [exists] /home/k-okada/catkin_ws/ws_msg/build
Devel Space:        [exists] /home/k-okada/catkin_ws/ws_msg/devel
Install Space:     [missing] /home/k-okada/catkin_ws/ws_msg/install
DESTDIR:                     None
------------------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
------------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
------------------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------------------------------------ 
Found '5' packages in 0.0 seconds. 
Starting ==> jsk_rviz_plugins                                                                                           
[jsk_rviz_plugins] ==> '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins/build_env.sh /usr/bin/cmake /home/k-okada/catkin_ws/ws_msg/src/jsk_visualization/jsk_rviz_plugins -DCATKIN_DEVEL_PREFIX=/home/k-okada/catkin_ws/ws_msg/devel -DCMAKE_INSTALL_PREFIX=/home/k-okada/catkin_ws/ws_msg/install' in '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins' 
-- Using CATKIN_DEVEL_PREFIX: /home/k-okada/catkin_ws/ws_msg/devel                                                      
-- Using CMAKE_PREFIX_PATH: /home/k-okada/catkin_ws/ws_msg/devel;/home/k-okada/catkin_ws/ws_euslisp/devel;/opt/ros/hydro 
-- This workspace overlays: /home/k-okada/catkin_ws/ws_msg/devel;/home/k-okada/catkin_ws/ws_euslisp/devel;/opt/ros/hydro 
-- Using PYTHON_EXECUTABLE: /usr/bin/python                                                                             
-- Python version: 2.7                                                                                                  
-- Using Debian Python package layout                                                                                   
-- Using CATKIN_ENABLE_TESTING: ON                                                                                      
-- Call enable_testing()                                                                                                
-- Using CATKIN_TEST_RESULTS_DIR: /home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins/test_results                    
-- Found gtest sources under '/usr/src/gtest': gtests will be built                                                     
-- catkin 0.5.90                                                                                                        
-- Using these message generators: gencpp;geneus;genlisp;genpy;genrb                                                    
-- message_generation Requires: gencpp;genlisp;genmsg;genpy                                                             
-- [roseus.cmake] generate all roseus messages                                                                          
-- jsk_rviz_plugins depends on                                                                                          
-- jsk_rviz_plugins: 7 messages, 3 services                                                                             
-- Configuring done                                                                                                     
-- Generating done                                                                                                      
-- Build files have been written to: /home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins                              
[jsk_rviz_plugins] <== '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins/build_env.sh /usr/bin/cmake /home/k-okada/catkin_ws/ws_msg/src/jsk_visualization/jsk_rviz_plugins -DCATKIN_DEVEL_PREFIX=/home/k-okada/catkin_ws/ws_msg/devel -DCMAKE_INSTALL_PREFIX=/home/k-okada/catkin_ws/ws_msg/install' finished with return code '0' 
[jsk_rviz_plugins] ==> '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins/build_env.sh /usr/bin/make -j1 -l1' in '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins' 
[  0%] Built target std_msgs_generate_messages_cpp                                                                      
[  0%] Built target geometry_msgs_generate_messages_cpp                                                                 
[  6%] Built target jsk_rviz_plugins_generate_messages_cpp                                                              
[  6%] Built target jsk_rviz_plugins_gencpp                                                                             
[  7%] Generating src/moc_overlay_image_display.cxx                                                                     
[  7%] Generating src/moc_overlay_camera_display.cxx                                                                    
[  8%] Generating src/moc_plotter_2d_display.cxx                                                                        
[  8%] Generating src/moc_pie_chart_display.cxx            
```

**Comment by garaemon** [comment]
Could you run catkin build without argument after catkin clean?

✉︎ Ryohei Ueda




On Tue, Feb 10, 2015 at 6:41 AM -0800, "Kei Okada" <notifications@github.com> wrote:












sorry I can not reproduce this

k-okada@ubuntu:~/catkin_ws/ws_msg$ catkin build jsk_rviz_plugins --force-cmake
------------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/k-okada/catkin_ws/ws_euslisp/devel:/opt/ros/hydro
Workspace:                   /home/k-okada/catkin_ws/ws_msg
Source Space:       [exists] /home/k-okada/catkin_ws/ws_msg/src
Build Space:        [exists] /home/k-okada/catkin_ws/ws_msg/build
Devel Space:        [exists] /home/k-okada/catkin_ws/ws_msg/devel
Install Space:     [missing] /home/k-okada/catkin_ws/ws_msg/install
DESTDIR:                     None
------------------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
------------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
------------------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------------------------------------ 
Found '5' packages in 0.0 seconds. 
Starting ==> jsk_rviz_plugins                                                                                           
[jsk_rviz_plugins] ==> '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins/build_env.sh /usr/bin/cmake /home/k-okada/catkin_ws/ws_msg/src/jsk_visualization/jsk_rviz_plugins -DCATKIN_DEVEL_PREFIX=/home/k-okada/catkin_ws/ws_msg/devel -DCMAKE_INSTALL_PREFIX=/home/k-okada/catkin_ws/ws_msg/install' in '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins' 
-- Using CATKIN_DEVEL_PREFIX: /home/k-okada/catkin_ws/ws_msg/devel                                                      
-- Using CMAKE_PREFIX_PATH: /home/k-okada/catkin_ws/ws_msg/devel;/home/k-okada/catkin_ws/ws_euslisp/devel;/opt/ros/hydro 
-- This workspace overlays: /home/k-okada/catkin_ws/ws_msg/devel;/home/k-okada/catkin_ws/ws_euslisp/devel;/opt/ros/hydro 
-- Using PYTHON_EXECUTABLE: /usr/bin/python                                                                             
-- Python version: 2.7                                                                                                  
-- Using Debian Python package layout                                                                                   
-- Using CATKIN_ENABLE_TESTING: ON                                                                                      
-- Call enable_testing()                                                                                                
-- Using CATKIN_TEST_RESULTS_DIR: /home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins/test_results                    
-- Found gtest sources under '/usr/src/gtest': gtests will be built                                                     
-- catkin 0.5.90                                                                                                        
-- Using these message generators: gencpp;geneus;genlisp;genpy;genrb                                                    
-- message_generation Requires: gencpp;genlisp;genmsg;genpy                                                             
-- [roseus.cmake] generate all roseus messages                                                                          
-- jsk_rviz_plugins depends on                                                                                          
-- jsk_rviz_plugins: 7 messages, 3 services                                                                             
-- Configuring done                                                                                                     
-- Generating done                                                                                                      
-- Build files have been written to: /home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins                              
[jsk_rviz_plugins] <== '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins/build_env.sh /usr/bin/cmake /home/k-okada/catkin_ws/ws_msg/src/jsk_visualization/jsk_rviz_plugins -DCATKIN_DEVEL_PREFIX=/home/k-okada/catkin_ws/ws_msg/devel -DCMAKE_INSTALL_PREFIX=/home/k-okada/catkin_ws/ws_msg/install' finished with return code '0' 
[jsk_rviz_plugins] ==> '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins/build_env.sh /usr/bin/make -j1 -l1' in '/home/k-okada/catkin_ws/ws_msg/build/jsk_rviz_plugins' 
[  0%] Built target std_msgs_generate_messages_cpp                                                                      
[  0%] Built target geometry_msgs_generate_messages_cpp                                                                 
[  6%] Built target jsk_rviz_plugins_generate_messages_cpp                                                              
[  6%] Built target jsk_rviz_plugins_gencpp                                                                             
[  7%] Generating src/moc_overlay_image_display.cxx                                                                     
[  7%] Generating src/moc_overlay_camera_display.cxx                                                                    
[  8%] Generating src/moc_plotter_2d_display.cxx                                                                        
[  8%] Generating src/moc_pie_chart_display.cxx

**Comment by k-okada** [comment]
yes it works well
```
catkin clean -a
catkin build
```
my setup is:

put euslisp,jskeus,geneus,roseus in /home/k-okada/catkin_ws/ws_euslisp/devel
and jsk_visualization in ws_msg/src



--
◉ Kei Okada

**Comment by garaemon** [comment]
Now i have the same error:
I set up my environment with `jsk.rosbuild --from-source hydro`
and run `catkin b drc_task_common`
https://gist.github.com/garaemon/759203e0d92e7f31db32

**Comment by garaemon** [comment]
However, I run `catkin b drc_task_common` after I see this error and the error has gone.

**Comment by garaemon** [comment]
Now travis has this issue:
https://travis-ci.org/jsk-ros-pkg/jsk_smart_apps/jobs/50499400

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_roseus/pull/232 will fix this

2015年2月13日金曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> Now travis has this issue:
> https://travis-ci.org/jsk-ros-pkg/jsk_smart_apps/jobs/50499400
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_smart_apps/issues/44#issuecomment-74113057>
> .
>


-- 
--
◉ Kei Okada

**Comment by k-okada** [comment]
see circle.yml to how to compile android apps
