### ISSUE TITLE
build.sh fails in jsk_ios_utils package because gitrious.org is discontinued.

### ISSUE THREAD

**Issue by yoshimalucky** [jsk-ros-pkg/jsk_smart_apps#55]
In the file below:
https://github.com/jsk-ros-pkg/jsk_smart_apps/blob/master/jsk_ios_utils/build.sh

git clone git://gitorious.org/~galbraithjoseph/boostoniphone/galbraithjosephs-boostoniphone.git $SRCDIR/boostonios
fails because gitorious.org is discontinued from 6/1.

I'm trying to use galbraithjoseph's boostonios but it does not exist.
Does anyone have source codes?
If so, it is better to include the files here or clone from a new git repo which has the copied files from the gitorious repo. Then, fix the script please.

**Comment by furushchev** [comment]
Currently, if you are not interested in development of iOS/ROS core, you can develop iOS apps using CocoaPods, not this repo.

**Comment by furushchev** [comment]
see https://github.com/furushchev/rosios

**Comment by yoshimalucky** [comment]
@furushchev The new project seems to work well! I could install it successfully and I'll try the tutorials next. Thank you very much!
